version: '3.8'

services:
  dev-db-mongodb:
    container_name: dev-ddd-mongodb-container
    image: mongo:7.0.7
    env_file:
      - .mongodb.env
    volumes:
      - ./container-data/mongodb:/data/mongodb
      # - temp_data/mongodb:/data/mongodb
    ports:
      - "27017:27017"
