START TRANSACTION;

INSERT INTO migrations (file) VALUES ('002.create-table-user-person.sql');

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR NOT NULL,
	salt VARCHAR NOT NULL,
  person_id UUID,
  FOREIGN KEY (person_id) REFERENCES persons(id)
);

CREATE TABLE IF NOT EXISTS persons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	first_name VARCHAR NOT NULL,
	last_name VARCHAR NOT NULL,
  birth_date TIMESTAMP NOT NULL
);

COMMIT;
