version: '3.8'

services:
  prod-mongo-rs0-1:
    image: mongo:6.0.13
    hostname: prod-mongo-rs0-1
    container_name: prod-mongo-rs0-1
    volumes:
      - ./container-data/mongo-rs0-1:/data/mongodb
    ports:
      - 27017:27017
    entrypoint: ["mongod", "--replSet", "prodReplicaSet", "--bind_ip", "localhost,prod-mongo-rs0-1"]

  prod-mongo-rs0-2:
    image: mongo:6.0.13
    hostname: prod-mongo-rs0-2
    container_name: prod-mongo-rs0-2
    ports:
      - 27018:27017
    volumes:
      - ./container-data/mongo-rs0-2:/data/mongodb
    entrypoint: ["mongod", "--replSet", "prodReplicaSet", "--bind_ip", "localhost,prod-mongo-rs0-2"]

  prod-mongo-rs0-3:
    image: mongo:6.0.13
    hostname: prod-mongo-rs0-3
    container_name: prod-mongo-rs0-3
    ports:
      - 27019:27017
    volumes:
      - ./container-data/mongo-rs0-3:/data/mongodb
    entrypoint: ["mongod", "--replSet", "prodReplicaSet", "--bind_ip", "localhost,prod-mongo-rs0-3"]

  mongosetup:
    image: mongo:6.0.13
    depends_on:
      - prod-mongo-rs0-1
      - prod-mongo-rs0-2
      - prod-mongo-rs0-3
    volumes:
      - ./mongo_setup.sh:/scripts/mongo_setup.sh
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]

  api-node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - prod-mongo-rs0-1
      - prod-mongo-rs0-2
      - prod-mongo-rs0-3
